name: leggedsnake-env
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib>=3.3.4
  - matplotlib-base>=3.3.4
  - numpy>=1.20.2
  - numpy-base>=1.20.2
  - numpydoc>=1.1.0
  - pymunk>=6.0.0
  - tqdm>=4.40.0
  - pip
  - pip:
    - pygad>=2.10.0
    - pylinkage>=0.5.0
