[tox]
envlist = py310,py311,py312,py313,py314,flake8

[testenv]
commands = python -m pytest tests/ -v
deps =
    pytest>=7.0.0
    pytest-cov>=4.0.0

[testenv:flake8]
deps = flake8
commands = flake8 src/leggedsnake/
